[book]
title = "Rust 语言入门 Introduction to Rust"
description = ""
authors = ["Shaohua <shaohua@biofan.org>"]
language = "zh-CN"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/xushaohua/intro-to-rust"

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
copyable = true
copy-js = true 
line-numbers = true
runnable = true

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter
