[workspace]
resolver = "2"

members = [
    "code/asynchronous",
    "code/closure",
    "code/concurrency",
    "code/containers",
    "code/enums",
    "code/error_handling",
    "code/expressions",
    "code/ffi",
    "code/iterators",
    "code/macros",
    "code/memory",
    "code/ownership",
    "code/pattern_matching",
    "code/primtives",
    "code/references",
    "code/smart_pointers",
    "code/stdlib",
    "code/strings",
    "code/structs",
    "code/traits"
]

exclude = [
    "book",
    "src",
    "tools",
]
