[workspace]

members = [
    "abstract-factory",
    "adapter",
    "bridge",
    "builder",
    "composite",
    "decorator",
    "facade",
    "factory-method",
    "flyweight",
    "prototype",
    "proxy",
    "simple-factory",
    "singleton",
]

resolver = "2"
