[workspace]
resolver = "2"

members = [ "code/asynchronous",
    "code/closure",
    "code/collections",
    "code/enums",
    "code/ffi",
    "code/memory",
    "code/references",
    "code/structs",
    "code/traits"
]

exclude = [
    "book",
    "src",
    "tools",
]
