[package]
name = "error_handling"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
r2d2 = "0.8.10"
thiserror = "2.0.3"

[[bin]]
name = "error_handling-use-panic"
path = "src/bin/use-panic.rs"
