[package]
name = "tokio_crate"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }

[[bin]]
name = "tokio_crate-hello-tokio"
path = "src/bin/hello-tokio.rs"
