[package]
name = "linux_ipc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eframe = { version = "0.28.1", default-features = false, features = ["wayland",  "wgpu"] }
egui = { version = "0.28.1", default-features = false }
egui_extras = { version = "0.28.1", default-features = false, features = ["default", "all_loaders"] }
image = { version = "0.25.2", default-features = false, features = ["jpeg", "png"] }
nc = "0.8.21"
serde = { version = "1.0.204", features = ["serde_derive"] }
serde_json = "1.0.120"


[[bin]]
name = "linux_ipc-pipe"
path = "src/bin/pipe.rs"

[[bin]]
name = "linux_ipc-barely-sim"
path = "src/bin/barely-sim.rs"

[[bin]]
name = "linux_ipc-dump-ops"
path = "src/bin/dump-ops.rs"
